### ISSUE TITLE
Make time limit change show point on accessibility histogram

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#16]
It would be nice if changing the vector isochrone slider moved a vertical line along the x-axis of the histogram, with a corresponding horizontal line to the y-axis where the vertical line intersects the histogram

**Comment by kuanb** [comment]
Definitely doable and something we could implement. Agreed as a stretch goal.

**Comment by hungryplanner** [comment]
Sketch of how to approach this:
- Add new parameter "minutes" to d3service.drawGraph. Suggest at front because "compare" parameter is optional.
- Within d3service.js:
  - change the index into data[] and compare[] from hard-coded 60 to "minutes" variable
  - change "within 1 hr." to a pretty-printed version of "minutes"
  - add svg line corresponding to that index.
- Within mapsController.js:
  - pass vectorIsos.val*5 as parameter

Note: text may become too wide to fit with times like "1 hr. 30 min.". SVG doesn't do text wrapping. Options:
1. Reduce font size to fit.
2. Abbreviate as "1h30"
3. Fake text wrapping, either:
- add a second .append("text") a la http://stackoverflow.com/questions/16701522/how-to-linebreak-an-svg-text-within-javascript , or
- use a <foreignobject> xhtml block within svg, a la http://stackoverflow.com/questions/24581623/svg-text-make-text-appear-in-2-lines

**Comment by hungryplanner** [comment]
to get _pretty-printed version of "minutes"_ requires changing d3Service.js:
line 2, add `$filter` parameter:
`coaxsApp.service('d3Service', function ($filter) {`
then invoke as `$filter('minuteconverter')(75)`

**Comment by ansoncfit** [comment]
017e9d closes

**Comment by ansoncfit** [comment]
2a9d4f closes

**Comment by ansoncfit** [comment]
2a9d4fb closes
