### ISSUE TITLE
Add station icons to rapid transit lines

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#9]
Using same simple icons as BRT corridors.
Onclick tooltips should have station names.

**Comment by kuanb** [comment]
What are the rapid transit lines? Are they a separate GeoJSON that has not yet been supplied or do they equate to the T lines? Either way, once the GeoJSON is provided (in fact, it can be combined with the stops.geojson that presently exists), we can easily incorporate.

**Comment by ansoncfit** [comment]
https://www.dropbox.com/s/8leeaaczukwz6ix/stations.geojson?dl=0

**Comment by mgpopinjay** [comment]
Potential phase 2 feature.

**Comment by ansoncfit** [comment]
Let's keep it a high priority.  This should be fairly simple (just
modifying/simplifying the logic for the BRT stops), and it was specifically
requested by users at the demo.

Anson Stewart

**Comment by kuanb** [comment]
Cool I can do this easily. Looks like they are, indeed, just the T stops so everything should be ready:
![image](https://cloud.githubusercontent.com/assets/6053396/8844483/7e325770-30e3-11e5-8308-2204899926fa.png)

**Comment by kuanb** [comment]
Hey guys this is working fine I just had a few comments to improve the `stations.geojson` and make it similar in structure to the others. If it's too hard, it's not a big deal - it's working fine now.

![image](https://cloud.githubusercontent.com/assets/6053396/8853640/9ff04296-3129-11e5-9e25-70bdaad7d80b.png)
1. Right now the coordinates under each property/stop are nested 1 too many times. Thus:

![image](https://cloud.githubusercontent.com/assets/6053396/8853658/b9570346-3129-11e5-9b8c-6f9ad3c306dd.png)

Ideally, going into coordinates would give me an array of 2 values but as it stands now it is a list with just one element and, within that, there are the 2 array items. This is fine and I can just nest one below but it would be cleaner (and identical to the other geojson) if this was not the case. This would allow me to use one function on both rather than a custom one for each which is less maintainable and not DRY (dont repeat yourself).
1. Standard JSON semantics would be "camelCase" but the current properties is in all CAPS. Wondering if it can be changed, just to make it same case structure as rest of code.

Thanks!

**Comment by kuanb** [comment]
Note (I know in the screen the icons are wrong was just using those as default).

**Comment by ansoncfit** [comment]
Sorry, my fault (though I'll try to pass the buck to QGIS geojson export).

Revised version in dropbox should address both issues.  

Also, renamed PREPAY to stationType to be consistent with BRT stops.json

**Comment by ansoncfit** [comment]
Also now in https://github.com/mitTransportAnalyst/altShapefiles

**Comment by kuanb** [comment]
awesome i was about to nag about putting them up on github :p thanks for the quick change

**Comment by ansoncfit** [comment]
GH isn't showing a map for stations.geojson.  LMK if you see an error with that.

**Comment by kuanb** [comment]
ill pull it through i think issue is that regex expressions for line breaks are in the geojson so it freaks out 
![image](https://cloud.githubusercontent.com/assets/6053396/8854408/bc942d00-312d-11e5-8f37-30b65a25fef4.png)

**Comment by kuanb** [comment]
Fixed it. geojson was exported with MultiPoint features but should have been just `Point`:

![image](https://cloud.githubusercontent.com/assets/6053396/8854612/b4fdbac4-312e-11e5-8e56-8c2333cf89ad.png)

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/8855934/d32248ba-3135-11e5-82c2-14a2b0c56599.png)

Might want to think about how to differentiate between the markers... Here I just changed opacity and size - but we can do something "better" - I'll think about it and come back to it. Chime in if you have thoughts as well of course.

**Comment by kuanb** [comment]
Perhaps when looking at one specific route all the T stops turn off? Then when back to "global" view they turn back on...
